added support for video file size
mojotech/react-native-image-picker pull request #1
Opened 2018-07-31 20:10 UTC by pi-chi

## Motivation

For Amica use case: DPA-12334, where checking the size of the video fails since there's no `fileSize` key on the response object.

## Test Plan

For this module, simply check response object for `fileSize`.

2018-07-31 20:19 UTC, cpjolicoeur requested changes
Can you please also update the README section for `fileSize` so that since that attribute is no longer photos only.

And might as well update `fileName` in the docs as well since it will now be available on photos and videos on both platforms.

Type field as well (it looks like the `putExtraFileInfo` method adds all 3 to the response object.

2018-07-31 20:19 UTC, cpjolicoeur commented on android/src/main/java/com/imagepicker/ImagePickerModule.java
> +        realPath = getRealPathFromURI(uri);
Where does `realPath` come from?  It appears it's lexically scoped to the `REQUEST_LAUNCH_IMAGE_LIBRARY` case only and not available here without us defining it again.

2018-07-31 20:19 UTC, cpjolicoeur commented on android/src/main/java/com/imagepicker/ImagePickerModule.java
> +        realPath = getRealPathFromURI(uri);
Same question here for lexical scope of this variable?

2018-07-31 20:24 UTC, pi-chi commented
Sure np

2018-07-31 20:27 UTC, pi-chi commented on android/src/main/java/com/imagepicker/ImagePickerModule.java
> +        realPath = getRealPathFromURI(uri);
Good question.. I noticed the author likes to just declare things and then use them where ever.. So I pretty much just stuck with that to keep it consistent.. If you look on line 386, you can see it's declared, and then used in couple other switch cases following..

2018-07-31 20:30 UTC, pi-chi commented on android/src/main/java/com/imagepicker/ImagePickerModule.java
> +        realPath = getRealPathFromURI(uri);
Er.. actually I'm an idiot, that was me putting in those other cases. Lol.. I can certainly bring their declarations up to line 377 where `uri` is!

2018-08-01 13:41 UTC, cpjolicoeur approved these changes

2018-08-01 13:41 UTC, merged